### PR TITLE
202106_bump

### PR DESCRIPTION
**Pull request by dkulacz**

### CODE REVIEW

**Comment by lukasz-mitka** [comment]
Great job figuring out gcc-10 issue!

**Review by darklukee — APPROVED** [review]

**Comment by lukasz-mitka** [comment]
go bigger: https://gcc.gnu.org/gcc-11/

**Comment by dkulacz** [comment]
root cause was gcc-10 has -fno-common enabled by default causing problems with newlib syscalls (multiple definitions of errno when linking etc)

**Comment by dkulacz** [comment]
> go bigger: https://gcc.gnu.org/gcc-11/

challenge accepted :)

**Pull request merged**
